
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class TicTacToe extends javax.swing.JFrame {
     char board[][] = {{'A','A','A'},
         {'A','A','A'},
         {'A','A','A'}};
     boolean player = true; //'X'
     boolean win = false;
     ImageIcon X = new ImageIcon(getClass().getResource("X.png"));
     ImageIcon O = new ImageIcon(getClass().getResource("O.png"));
     
    /**
     * Creates new form TicTacToe
     */
    public TicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Btn00 = new javax.swing.JButton();
        Btn01 = new javax.swing.JButton();
        Btn02 = new javax.swing.JButton();
        Btn10 = new javax.swing.JButton();
        Btn11 = new javax.swing.JButton();
        Btn12 = new javax.swing.JButton();
        Btn20 = new javax.swing.JButton();
        Btn21 = new javax.swing.JButton();
        Btn22 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("TIC TAC TOE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 33, 210, -1));

        Btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn00ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn00, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 50, 50));

        Btn01.setToolTipText("");
        Btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn01ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn01, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 50, 50));

        Btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn02ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn02, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 50, 50));

        Btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn10ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 50, 50));

        Btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn11ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 50, 50));

        Btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn12ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 50, 50));

        Btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn20ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 50, 50));

        Btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn21ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 50, 50));

        Btn22.setBackground(new java.awt.Color(255, 255, 255));
        Btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn22ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 50, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn10ActionPerformed
        // TODO add your handling code here:
        select(this.Btn10,10);
    }//GEN-LAST:event_Btn10ActionPerformed

    private void Btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn20ActionPerformed
        // TODO add your handling code here:
        select(this.Btn20,20);
    }//GEN-LAST:event_Btn20ActionPerformed

    private void Btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn00ActionPerformed
        // TODO add your handling code here:
        select(this.Btn00,00);   // to make a function so that every button csn use it
        
    }//GEN-LAST:event_Btn00ActionPerformed

    private void Btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn01ActionPerformed
        // TODO add your handling code here:
        select(this.Btn01,01);
    }//GEN-LAST:event_Btn01ActionPerformed

    private void Btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn02ActionPerformed
        // TODO add your handling code here:
        select(this.Btn02,02);
    }//GEN-LAST:event_Btn02ActionPerformed

    private void Btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn11ActionPerformed
        // TODO add your handling code here:
        select(this.Btn11,11);
    }//GEN-LAST:event_Btn11ActionPerformed

    private void Btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn12ActionPerformed
        // TODO add your handling code here:
        select(this.Btn12,12);
    }//GEN-LAST:event_Btn12ActionPerformed

    private void Btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn21ActionPerformed
        // TODO add your handling code here:
        select(this.Btn21,21);
    }//GEN-LAST:event_Btn21ActionPerformed

    private void Btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn22ActionPerformed
        // TODO add your handling code here:
        select(this.Btn22,22);
    }//GEN-LAST:event_Btn22ActionPerformed
      public void select(JButton Btn ,int cell){
          int row =cell/10;
          int col = cell%10;
          if(player){
              board[row][col]= 'x';
              Btn.setIcon(X);
          } else{
              board[row][col]= 'O';
              Btn.setIcon(O);           
          }
          player = !player;
          Btn.setEnabled(false);
          checkWin();
      }
      
      //check for row win
      public void checkWin(){
        
        //check for row win
        for (int i=0;i<3;i++){
            if ((board[i][0] == board [i][1]) && 
                    (board[i][0] == board [i][2]) &&
                    (board[i][0] != 'A')){
                JOptionPane.showMessageDialog(this, "Player " 
                        + board[i][0] + " wins...!!!");
                disableAllButtons();
                win = true;
            }
        }
        
        //check for column win
        for (int i=0;i<3;i++){
            if ((board[0][i] == board [1][i]) && 
                    (board[0][i] == board [2][i]) &&
                    (board[0][i] != 'A')){
                JOptionPane.showMessageDialog(this, "Player " 
                        + board[0][i] + " wins...!!!");
                disableAllButtons();
                win = true;
            }
        }
        
        //check for diagonal win
        
        if (((board[0][0] == board [1][1]) && 
                (board[0][0] == board [2][2]) &&
                (board[0][0] != 'A')) || 
                (((board[0][2] == board [1][1]) && 
                (board[0][2] == board [2][0]) &&
                (board[0][2] != 'A')))){
            JOptionPane.showMessageDialog(this, "Player " 
                    + board[1][1] + " wins...!!!");
            disableAllButtons();
            win = true;
        }
        
        if (win){
            //ask to play again
            int answer = JOptionPane.showConfirmDialog(this, "Do you want to play again ?", " Play again", JOptionPane.YES_NO_OPTION);

            if (answer == JOptionPane.YES_OPTION){
                restartGame();
            }else{
                System.exit(0);
            }
        }
    }
    
    public void disableAllButtons(){
        this.Btn00.setEnabled(false);
        this.Btn01.setEnabled(false);
        this.Btn02.setEnabled(false);
        this.Btn10.setEnabled(false);
        this.Btn11.setEnabled(false);
        this.Btn12.setEnabled(false);
        this.Btn20.setEnabled(false);
        this.Btn21.setEnabled(false);
        this.Btn22.setEnabled(false);
    }
    
    public void restartGame(){
        this.Btn00.setEnabled(true);
        this.Btn00.setIcon(null);
        this.Btn01.setEnabled(true);
        this.Btn01.setIcon(null);
        this.Btn02.setEnabled(true);
        this.Btn02.setIcon(null);
        this.Btn10.setEnabled(true);
        this.Btn10.setIcon(null);
        this.Btn11.setEnabled(true);
        this.Btn11.setIcon(null);
        this.Btn12.setEnabled(true);
        this.Btn12.setIcon(null);
        this.Btn20.setEnabled(true);
        this.Btn20.setIcon(null);
        this.Btn21.setEnabled(true);
        this.Btn21.setIcon(null);
        this.Btn22.setEnabled(true);
        this.Btn22.setIcon(null);
        
        player = true;
        win = false;
        
        for(int i=0;i<3;i++){
            for(int j=0;j<3;j++){
                board[i][j] = 'A';
            }
        

        }}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn00;
    private javax.swing.JButton Btn01;
    private javax.swing.JButton Btn02;
    private javax.swing.JButton Btn10;
    private javax.swing.JButton Btn11;
    private javax.swing.JButton Btn12;
    private javax.swing.JButton Btn20;
    private javax.swing.JButton Btn21;
    private javax.swing.JButton Btn22;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
